# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='sdcard.proto',
  package='',
  serialized_pb='\n\x0csdcard.proto\"Q\n\x06\x46older\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08\x66ullpath\x18\x02 \x02(\t\x12\x18\n\x07\x66olders\x18\x03 \x03(\x0b\x32\x07.Folder\x12\r\n\x05\x66iles\x18\x04 \x03(\t')




_FOLDER = descriptor.Descriptor(
  name='Folder',
  full_name='Folder',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='Folder.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fullpath', full_name='Folder.fullpath', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='folders', full_name='Folder.folders', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='files', full_name='Folder.files', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=97,
)

_FOLDER.fields_by_name['folders'].message_type = _FOLDER
DESCRIPTOR.message_types_by_name['Folder'] = _FOLDER

class Folder(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FOLDER
  
  # @@protoc_insertion_point(class_scope:Folder)

# @@protoc_insertion_point(module_scope)
